-- create table person
-- (
--     id         integer      not null,
--
--     name       varchar(255) not null,
--
--     location   varchar(255),
--
--     birth_date timestamp,
--
--     primary key (id)
-- );
-- you don't need to create table because its taken care of in schema update